-- Selection queries. 
SELECT * FROM STATIC_CONFIGURATION; 
SELECT * FROM SOC_MUL_USER; 
SELECT * FROM MULTIPLICATION; 
SELECT * FROM MULTIPLICATION_RESULT_ATTEMPT; 


-- Drop Table Commands. 
DROP TABLE SOC_MUL_USER; 
DROP TABLE MULTIPLICATION; 
DROP TABLE MULTIPLICATION_RESULT_ATTEMPT; 
DROP TABLE STATIC_CONFIGURATION; 