-- Selection queries. 
SELECT * FROM STATIC_CONFIGURATION; 
SELECT * FROM SOC_MUL_USER; 
SELECT * FROM MULTIPLICATION; 
SELECT * FROM MULTIPLICATION_RESULT_ATTEMPT; 


-- Drop Table Commands. 
DELETE FROM MULTIPLICATION_RESULT_ATTEMPT; 
DELETE FROM SOC_MUL_USER; 
DELETE FROM MULTIPLICATION; 
DELETE FROM STATIC_CONFIGURATION; 

INSERT INTO STATIC_CONFIGURATION(CONFIGURATION_NAME, CONFIGURATION_VALUE) VALUES('USER_ID_COUNT', 0)
INSERT INTO STATIC_CONFIGURATION(CONFIGURATION_NAME, CONFIGURATION_VALUE) VALUES('MULTIPLICATION_ID_COUNT', 0); 
INSERT INTO STATIC_CONFIGURATION(CONFIGURATION_NAME, CONFIGURATION_VALUE) VALUES('MRA_ID', 0);

DROP TABLE SOC_MUL_USER; 
DROP TABLE MULTIPLICATION; 
DROP TABLE MULTIPLICATION_RESULT_ATTEMPT; 
DROP TABLE STATIC_CONFIGURATION; 