-- Create Database. 
CREATE DATABASE SocMulDB; 
USE SocMulDB; 

-- Create USER for Database. 
CREATE LOGIN SocMulUser WITH PASSWORD = 'socMul@2020'; 

-- Multiplication table. 
CREATE TABLE MULTIPLICATION (
    MULTIPLICATION_ID INT NOT NULL, 
    OPERAND_1 INT NOT NULL, 
    OPERAND_2 INT NOT NULL,
    
    PRIMARY KEY (MULTIPLICATION_ID)
); 

-- User table. 
CREATE TABLE SOC_MUL_USER (
    USER_ID INT NOT NULL, 
    ALIAS VARCHAR(100) NOT NULL,
    
    PRIMARY KEY (USER_ID)
); 

-- Multiplication result attempt table. 
CREATE TABLE MULTIPLICATION_RESULT_ATTEMPT (
    ID INT NOT NULL, 
    CORRECT BIT, 
    RESULT_ATTEMPT INT NOT NULL, 
    MULTIPLICATION_ID INT NOT NULL, 
    USER_ID INT NOT NULL,
    
    PRIMARY KEY (ID),
    FOREIGN KEY (MULTIPLICATION_ID) REFERENCES MULTIPLICATION(MULTIPLICATION_ID),
    FOREIGN KEY (USER_ID) REFERENCES SOC_MUL_USER(USER_ID)
); 

-- Create STATIC_CONFIGURATION_TABLE. 
CREATE TABLE STATIC_CONFIGURATION (
    CONFIGURATION_NAME VARCHAR(25) NOT NULL, 
    CONFIGURATION_VALUE INT NOT NULL,
    
    PRIMARY KEY (CONFIGURATION_NAME));
    
--- Static data values. 
INSERT INTO STATIC_CONFIGURATION(CONFIGURATION_NAME, CONFIGURATION_VALUE) VALUES('USER_ID_COUNT', 0)
INSERT INTO STATIC_CONFIGURATION(CONFIGURATION_NAME, CONFIGURATION_VALUE) VALUES('MULTIPLICATION_ID_COUNT', 0); 
INSERT INTO STATIC_CONFIGURATION(CONFIGURATION_NAME, CONFIGURATION_VALUE) VALUES('MRA_ID', 0);
